### ISSUE TITLE
Help: Pi Zero not powering up

### ISSUE THREAD

**Issue by maded2** [LinuxJedi/AmigaRGBtoHDMI#10]
hi,
   Thank you for the putting the work in for this project.   

   I have A500 Rev 3 board.  I've just made this board.  It appears that the Pi Zero wouldn't boot up when plugged into the RGBtoHDMI adaptor, but it appears to boot when not plugin.   Any pointer to debug will be very helpful.  I've checked the soldering and it appears to be good.

thanks,
eddie

**Comment by LinuxJedi** [comment]
Ah! So, I don't have a rev 3 board (I've been trying to get hold of one at a reasonable price for a while) but I believe the problem is that CSYNC isn't routed to Denise on it. I know how to solve this on an A1000 but I need to look into diagrams of the A500 rev 3 to see how to work around it.

I'll get back to you once I figure this out.

**Comment by maded2** [comment]
fantastic,  so will this caused the Pi zero not booting up?

**Comment by LinuxJedi** [comment]
OK, found the schematic (https://museum.syssrc.com/static/Amiga_500_Introduction.pdf).

The Pi should be booting but won't do anything until it gets a CSYNC signal, the button will not function either. If you are lucky you might see a flash of colour but this usually happens faster than monitors can show. The monitor will go back into DPMS immediately.

Did you get as far as the firmware recovery screen for first time boot?

The workaround for rev 3 CSYNC is to connect U41 pin 9 to pin 32 on Denise, this will provide CSYNC on the Denise which the RGBtoHDMI board can pick up.

**Comment by maded2** [comment]
ok, I will give it a try tomorrow.  I haven't make it to the recovery screen yet, as I said the Pi zero appears not to boot at all.

**Comment by LinuxJedi** [comment]
OK, there may be something else at play as well then. Can you please attach a good as possible photo of the CPLD soldering and the underside surface mount soldering?

Also did the RGB standard Amiga connector work whilst the board was plugged in?

**Comment by maded2** [comment]
![1638893569907](https://user-images.githubusercontent.com/531234/145065332-95688019-e70c-4b2c-b09e-61e2aa8a624b.jpg)
![1638893548533](https://user-images.githubusercontent.com/531234/145065355-5e3ed18c-7071-4ad4-b167-840e2fe2dc77.jpg)

the Amiga is working as expected.  I get a the B&W composite video signal and it display fine (I don't have a CRT to use the RGB video out, that's why I want to get this board to work)

**Comment by LinuxJedi** [comment]
A couple of things to check, first of all there might be a solder bridge here:

![145065355-5e3ed18c-7071-4ad4-b167-840e2fe2dc77](https://user-images.githubusercontent.com/636271/145066656-108e0e6b-52fa-45a1-bd7c-41425416c6d9.jpg)

Also, with a multimeter try to do a continuity test on one of the capacitors on the underside, this would indicate a short between 3.3v and ground which would stop the Pi booting.

**Comment by maded2** [comment]
I will reflow those pins tomorrow.  continuity test  is showing a short across the capacitor.  Will reflow all the passives as well tomorrow under the scope.

many thanks.

**Comment by LinuxJedi** [comment]
You might need to replace the capacitors if the reflow doesn't fix it, occasionally you can get a bad one. The short will definitely be the problem. The two pins to the right of the ones I highlighted I think are 3.3v and GND, so check if there is a short there too. Possibly check the right side of the chip, I can't tell if it is blur or if there are bridges there.

**Comment by maded2** [comment]
![1638974690628](https://user-images.githubusercontent.com/531234/145228473-2a047268-464a-4a55-bae2-656fd3d2b5e5.jpg)
![1638974690619](https://user-images.githubusercontent.com/531234/145228481-2491a9ca-e1f5-4139-aded-15ef91fd3641.jpg)
![1638974690608](https://user-images.githubusercontent.com/531234/145228486-c5b0fe2b-7ab0-48e0-98f2-2955a8df4f93.jpg)

fantastic, everything working now.  one of the smd passive had a short.   Then there was no sync signal.  I use your suggestion of  csync from U41 pin9 workaround, this works really well.

many thanks for your help
