### ISSUE TITLE
Got one working (A1000)! But can't clear up noise.

### ISSUE THREAD

**Issue by goose2000** [LinuxJedi/AmigaRGBtoHDMI#11]
Hi - Finished building and flashing and booting up v3 board tonight. It looks pretty good, but seems no matter I still get lines and a little noise even after I run the autoconfiguration. Tried a few times. My CSYNC is connected to the RGBtoHDMI pin and soldered to the U6 chip.

The TV I am using is a small and odd size resolution: 1360 x 768 - It's like a RV travel TV.

Thanks for any ideas

**Comment by LinuxJedi** [comment]
Can you please take a photo of the output, a photo of the main menu on the software and a photo of the sampling menu? This should help figure out where the problem lies.

Also, are you running the auto-calibration on a static image (eg. Kickstart 1.2/1.3 screen?), it will make a bad decision if there is any motion on the image.

**Comment by goose2000** [comment]
Think we can close this one L.J. - I moved on to a second board, where I did a better job on the CPLD. Hooked it up, flashed this one and it performs beautifully ! So, I had some build quality on original board. 

![PXL_20211209_225411364](https://user-images.githubusercontent.com/2395298/145489723-56e6e7f4-246b-44bf-950f-508a1e4396dd.jpg)

**Comment by LinuxJedi** [comment]
I'm glad you got it working. It could well have been a tiny solder bridge around a couple of the Xilinx pins that did it. Sometimes they are invisible to the naked eye (I've fried a Pi Zero with one thinner than a human hair).

**Comment by goose2000** [comment]
I went back to wonky board with a new magnifier I got in the mail from Mouser today. Pretty sure I found a little bridge on these two pins, think this is probably my OG problem...
![download](https://user-images.githubusercontent.com/2395298/145627325-bdb6639c-ce04-442d-877e-91be3a445d36.png)

**Comment by LinuxJedi** [comment]
I believe that is the output of two different colours shorted. So that would definitely do it. A bit of flux and a light touch of the soldering iron should fix that.

**Comment by goose2000** [comment]
Yep!
![52c2c8fc-aff0-4334-87f9-127b3dccb7a0](https://user-images.githubusercontent.com/2395298/145647958-424451b6-ea46-4fb3-8396-65c5ad697e95.png)
!
