### ISSUE TITLE
Other CPLD

### ISSUE THREAD

**Issue by shred** [LinuxJedi/AmigaRGBtoHDMI#16]
The XC9572XL seems to be out of stock everywhere until 2024, at least for hobbyists.

Is there a way to redesign the adapters using a CPLD that is still available? (I don't know much about CPLDs, so I'm sorry if this is a really stupid question. :wink: )

**Comment by LinuxJedi** [comment]
One builder has done a redesign to use the PLCC variant which had some availability. But I believe they are out of stock in most places now too. BGA variant is still available but it is not cheap (or easy to solder if you don't have the equipment to do it).

As for other brands of CPLD, it is possible, but the same supply issue pretty much exists and the flashing software would need to be updated accordingly (this may be more difficult).

**Comment by shred** [comment]
Well, since the Raspberry Pi Zero is also out of stock (or sold at online auctions for 50€ or more), I guess we'll have to wait patiently.

Thank you for the answer. I will close this ticket.
