### ISSUE TITLE
Video artifacting

### ISSUE THREAD

**Issue by mudmin** [LinuxJedi/AmigaRGBtoHDMI#17]
Hi!  Thanks so much for this awesome project. 

I'll be the first to say that I don't know what I don't know when it comes to Amiga stuff.  I've assembled a board and tested every pin for shorts with the mm, but I'm getting some artifacting on the screen. I'm guessing you've seen this before and might be able to point me in the right direction.  Here's a little 3 second clip.   https://photos.app.goo.gl/JEaZk1dhBtpuopQu9

**Comment by LinuxJedi** [comment]
Hi @mudmin,

Did you run the auto-calibration in the RGBtoHDMI menu? It looks like it is just out of phase to me.

**Comment by mudmin** [comment]
Oh my gosh. Thank you. I totally missed that and now it is perfect. You are a rockstar.

**Comment by LinuxJedi** [comment]
Not a problem at all, glad it works for you now. Enjoy!
