### ISSUE TITLE
Gerber files, graphics need to be moved to silkscreen layer

### ISSUE THREAD

**Issue by goose2000** [LinuxJedi/AmigaRGBtoHDMI#9]
Hi, I ran into the issue today at PCBWay :

Hi John, For PCB order No. W234910ASB2,please see the image,the cartoon image can not be made on solder mask layer because the width of line is too thin. Please consider move it to silkscreen layer,and expand line to 0.075mm at least. Waitting for your new gerber file.

They want the image moved and line bigger. I don't know how to edit the gerber files / PCB software.

https://pcbwayfile.s3-us-west-2.amazonaws.com/msgfile/21/10/04/2214162170132t.png

**Comment by LinuxJedi** [comment]
Huh... they didn't have a problem with it before now. I'll remove the image and update the gerbers when I get time later today.

**Comment by LinuxJedi** [comment]
The logo has been removed from the board, gerbers updated on this tree and PCBWay's project page has been updated.

**Comment by goose2000** [comment]
Thanks Andrew, FWIW I liked the logo ;) Will give these a re-upload.
